/* ================= RESUME CORE ================= */
export const SET_CURRENT_RESUME = 'SET_CURRENT_RESUME';
export const UPDATE_CURRENT_RESUME = 'UPDATE_CURRENT_RESUME';
export const RESET_CURRENT_RESUME = 'RESET_CURRENT_RESUME';

/* ================= CREATE RESUME ================= */
export const CREATE_RESUME_REQUEST = 'CREATE_RESUME_REQUEST';
export const CREATE_RESUME_SUCCESS = 'CREATE_RESUME_SUCCESS';
export const CREATE_RESUME_FAILURE = 'CREATE_RESUME_FAILURE';

/* ================= FETCH RESUME ================= */
export const FETCH_RESUME_REQUEST = 'FETCH_RESUMES_REQUEST';
export const FETCH_RESUME_SUCCESS = 'FETCH_RESUMES_SUCCESS';
export const FETCH_RESUME_FAILURE = 'FETCH_RESUMES_FAILURE';

/* ================= FETCH RESUMES ================= */
export const FETCH_RESUMES_REQUEST = 'FETCH_RESUMES_REQUEST';
export const FETCH_RESUMES_SUCCESS = 'FETCH_RESUMES_SUCCESS';
export const FETCH_RESUMES_FAILURE = 'FETCH_RESUMES_FAILURE';

/* ================= UPDATE SECTIONS ================= */
export const UPDATE_TITLE_REQUEST = 'UPDATE_TITLE_REQUEST';
export const UPDATE_TITLE_SUCCESS = 'UPDATE_TITLE_SUCCESS';
export const UPDATE_TITLE_FAILURE = 'UPDATE_TITLE_FAILURE';

export const UPDATE_PERSONAL_INFO_REQUEST = 'UPDATE_PERSONAL_INFO_REQUEST';
export const UPDATE_PERSONAL_INFO_SUCCESS = 'UPDATE_PERSONAL_INFO_SUCCESS';
export const UPDATE_PERSONAL_INFO_FAILURE = 'UPDATE_PERSONAL_INFO_FAILURE';

export const UPDATE_EDUCATION_REQUEST = 'UPDATE_EDUCATION_REQUEST';
export const UPDATE_EDUCATION_SUCCESS = 'UPDATE_EDUCATION_SUCCESS';
export const UPDATE_EDUCATION_FAILURE = 'UPDATE_EDUCATION_FAILURE';

export const UPDATE_EXPERIENCE_REQUEST = 'UPDATE_EXPERIENCE_REQUEST';
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS';
export const UPDATE_EXPERIENCE_FAILURE = 'UPDATE_EXPERIENCE_FAILURE';

export const UPDATE_SKILLS_REQUEST = 'UPDATE_SKILLS_REQUEST';
export const UPDATE_SKILLS_SUCCESS = 'UPDATE_SKILLS_SUCCESS';
export const UPDATE_SKILLS_FAILURE = 'UPDATE_SKILLS_FAILURE';

export const UPDATE_SOCIAL_LINKS_REQUEST = 'UPDATE_SOCIAL_LINKS_REQUEST';
export const UPDATE_SOCIAL_LINKS_SUCCESS = 'UPDATE_SOCIAL_LINKS_SUCCESS';
export const UPDATE_SOCIAL_LINKS_FAILURE = 'UPDATE_SOCIAL_LINKS_FAILURE';

/* ================= DELETE ================= */
export const DELETE_RESUME_REQUEST = 'DELETE_RESUME_REQUEST';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';
export const DELETE_RESUME_FAILURE = 'DELETE_RESUME_FAILURE';
