export const UPDATE_CURRENT_RESUME = 'UPDATE_CURRENT_RESUME';
export const SET_CURRENT_RESUME = 'SET_CURRENT_RESUME';
export const SAVE_RESUME_REQUEST = 'SAVE_RESUME_REQUEST';
export const SAVE_RESUME_SUCCESS = 'SAVE_RESUME_SUCCESS';
export const SAVE_RESUME_FAILURE = 'SAVE_RESUME_FAILURE';

export const FETCH_RESUMES_REQUEST = 'FETCH_RESUMES_REQUEST';
export const FETCH_RESUMES_SUCCESS = 'FETCH_RESUMES_SUCCESS';
export const FETCH_RESUMES_FAILURE = 'FETCH_RESUMES_FAILURE';
